=== KronosOceanus/javaSE/JAXP解析XML/java.dtd
<!ELEMENT classes (java,net,php,ios)>

<!ELEMENT java (teachers?,students?)>
<!ELEMENT net (teachers?,students?)>
<!ELEMENT php (teachers?,students?)>
<!ELEMENT ios (teachers?,students?)>

<!ELEMENT teachers (teacher*)>
<!ELEMENT teacher EMPTY>
<!ELEMENT students (student*)>
<!ELEMENT student (name,sex,age)>

<!ATTLIST classes name CDATA #IMPLIED>
<!ATTLIST java name CDATA #IMPLIED>
<!ATTLIST net name CDATA #IMPLIED>
<!ATTLIST php name CDATA #IMPLIED>
<!ATTLIST ios name CDATA #IMPLIED>

<!ATTLIST teacher name CDATA #IMPLIED>
<!ATTLIST teacher sex CDATA #IMPLIED>
<!ATTLIST teacher age CDATA #IMPLIED>

<!ELEMENT name (#PCDATA)>
<!ELEMENT sex (#PCDATA)>
<!ELEMENT age (#PCDATA)>

<!ATTLIST teacher id ID #IMPLIED>
<!ATTLIST student id ID #IMPLIED>

=== KronosOceanus/javaSE/JAXP解析XML/java.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE classes SYSTEM "java.dtd">
<classes name="华">
    <java name="CSDNJava01班">
        <teachers>
            <teacher id="id" />
            <teacher age="28" name="刘丽华" sex="女"/>
            <teacher age="28" name="刘华" sex="男"/>
            <teacher age="28" name="华" sex="女"/>
        </teachers>
        <students>
            <student id="x121">
                <name>王亮</name>
                <sex>女</sex>
                <age>28</age>
            </student>
        </students>
    </java>
    <net name="华"/>
    <php name="CSDNPhp01班"/>
    <ios name="CSDNIos01班"/>
</classes>
